# Form implementation generated from reading ui file 'ui/cash.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CASH(object):
    def setupUi(self, CASH):
        CASH.setObjectName("CASH")
        CASH.resize(1217, 876)
        CASH.setStyleSheet("QWidget {\n"
"    background-color: white;\n"
"}")
        self.gridLayout_7 = QtWidgets.QGridLayout(CASH)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_info = QtWidgets.QWidget(parent=CASH)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_info.sizePolicy().hasHeightForWidth())
        self.widget_info.setSizePolicy(sizePolicy)
        self.widget_info.setStyleSheet("QWidget {\n"
"    background: #CCDCE8;  /* холодный металлик с голубым оттенком */\n"
"\n"
"    color: #1C1C1E;\n"
"\n"
"    font-family: \"SF Pro Text\", \"Helvetica Neue\", \"Helvetica\", \"Arial\";\n"
"    font-size: 13px;\n"
"\n"
"    border: 1px solid #8EA5B8;\n"
"    border-radius: 12px;\n"
"}")
        self.widget_info.setObjectName("widget_info")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_info)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.general_information = QtWidgets.QWidget(parent=self.widget_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.general_information.sizePolicy().hasHeightForWidth())
        self.general_information.setSizePolicy(sizePolicy)
        self.general_information.setStyleSheet("")
        self.general_information.setObjectName("general_information")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.general_information)
        self.gridLayout_3.setContentsMargins(12, -1, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_title = QtWidgets.QLabel(parent=self.general_information)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        self.label_title.setAutoFillBackground(False)
        self.label_title.setStyleSheet("")
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout_2.addWidget(self.label_title, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_calendar = QtWidgets.QLabel(parent=self.general_information)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_calendar.sizePolicy().hasHeightForWidth())
        self.label_calendar.setSizePolicy(sizePolicy)
        self.label_calendar.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_calendar.setObjectName("label_calendar")
        self.horizontalLayout_3.addWidget(self.label_calendar)
        self.lineEdit_calendar = QtWidgets.QLineEdit(parent=self.general_information)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_calendar.sizePolicy().hasHeightForWidth())
        self.lineEdit_calendar.setSizePolicy(sizePolicy)
        self.lineEdit_calendar.setMaximumSize(QtCore.QSize(25, 16777215))
        self.lineEdit_calendar.setText("")
        self.lineEdit_calendar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_calendar.setObjectName("lineEdit_calendar")
        self.horizontalLayout_3.addWidget(self.lineEdit_calendar)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_weekend = QtWidgets.QLabel(parent=self.general_information)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_weekend.sizePolicy().hasHeightForWidth())
        self.label_weekend.setSizePolicy(sizePolicy)
        self.label_weekend.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_weekend.setObjectName("label_weekend")
        self.horizontalLayout_5.addWidget(self.label_weekend)
        self.lineEdit_weekend = QtWidgets.QLineEdit(parent=self.general_information)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_weekend.sizePolicy().hasHeightForWidth())
        self.lineEdit_weekend.setSizePolicy(sizePolicy)
        self.lineEdit_weekend.setMaximumSize(QtCore.QSize(25, 16777215))
        self.lineEdit_weekend.setText("")
        self.lineEdit_weekend.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_weekend.setObjectName("lineEdit_weekend")
        self.horizontalLayout_5.addWidget(self.lineEdit_weekend)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_work = QtWidgets.QLabel(parent=self.general_information)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_work.sizePolicy().hasHeightForWidth())
        self.label_work.setSizePolicy(sizePolicy)
        self.label_work.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_work.setObjectName("label_work")
        self.horizontalLayout_4.addWidget(self.label_work)
        self.lineEdit_work = QtWidgets.QLineEdit(parent=self.general_information)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_work.sizePolicy().hasHeightForWidth())
        self.lineEdit_work.setSizePolicy(sizePolicy)
        self.lineEdit_work.setMaximumSize(QtCore.QSize(25, 16777215))
        self.lineEdit_work.setText("")
        self.lineEdit_work.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_work.setObjectName("lineEdit_work")
        self.horizontalLayout_4.addWidget(self.lineEdit_work)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.general_information)
        self.secondary_information = QtWidgets.QWidget(parent=self.widget_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.secondary_information.sizePolicy().hasHeightForWidth())
        self.secondary_information.setSizePolicy(sizePolicy)
        self.secondary_information.setObjectName("secondary_information")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.secondary_information)
        self.gridLayout_4.setContentsMargins(12, -1, -1, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setVerticalSpacing(4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_day_zp = QtWidgets.QLabel(parent=self.secondary_information)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_day_zp.sizePolicy().hasHeightForWidth())
        self.label_day_zp.setSizePolicy(sizePolicy)
        self.label_day_zp.setObjectName("label_day_zp")
        self.gridLayout_5.addWidget(self.label_day_zp, 0, 0, 1, 1)
        self.spinBox_zp = QtWidgets.QSpinBox(parent=self.secondary_information)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_zp.sizePolicy().hasHeightForWidth())
        self.spinBox_zp.setSizePolicy(sizePolicy)
        self.spinBox_zp.setObjectName("spinBox_zp")
        self.gridLayout_5.addWidget(self.spinBox_zp, 0, 1, 1, 1)
        self.label_day_avans = QtWidgets.QLabel(parent=self.secondary_information)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_day_avans.sizePolicy().hasHeightForWidth())
        self.label_day_avans.setSizePolicy(sizePolicy)
        self.label_day_avans.setObjectName("label_day_avans")
        self.gridLayout_5.addWidget(self.label_day_avans, 1, 0, 1, 1)
        self.spinBox_avans = QtWidgets.QSpinBox(parent=self.secondary_information)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_avans.sizePolicy().hasHeightForWidth())
        self.spinBox_avans.setSizePolicy(sizePolicy)
        self.spinBox_avans.setObjectName("spinBox_avans")
        self.gridLayout_5.addWidget(self.spinBox_avans, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.secondary_information)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.widget_calendar = QtWidgets.QWidget(parent=self.widget_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_calendar.sizePolicy().hasHeightForWidth())
        self.widget_calendar.setSizePolicy(sizePolicy)
        self.widget_calendar.setStyleSheet("QWidget {\n"
"    background: #FFFFFF;\n"
"\n"
"    color: #1C1C1E;\n"
"\n"
"    font-family: \"SF Pro Text\", \"Helvetica Neue\", \"Helvetica\", \"Arial\";\n"
"    font-size: 13px;\n"
"\n"
"    border: 1px solid #D8D8DB;\n"
"    border-radius: 12px;\n"
"}")
        self.widget_calendar.setObjectName("widget_calendar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_calendar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_calendar = QtWidgets.QTableWidget(parent=self.widget_calendar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_calendar.sizePolicy().hasHeightForWidth())
        self.tableWidget_calendar.setSizePolicy(sizePolicy)
        self.tableWidget_calendar.setObjectName("tableWidget_calendar")
        self.tableWidget_calendar.setColumnCount(0)
        self.tableWidget_calendar.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_calendar)
        self.horizontalLayout_2.addWidget(self.widget_calendar)
        self.widget_calendar_2 = QtWidgets.QWidget(parent=self.widget_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_calendar_2.sizePolicy().hasHeightForWidth())
        self.widget_calendar_2.setSizePolicy(sizePolicy)
        self.widget_calendar_2.setStyleSheet("QWidget {\n"
"    background: #FFFFFF;\n"
"\n"
"    color: #1C1C1E;\n"
"\n"
"    font-family: \"SF Pro Text\", \"Helvetica Neue\", \"Helvetica\", \"Arial\";\n"
"    font-size: 13px;\n"
"\n"
"    border: 1px solid #D8D8DB;\n"
"    border-radius: 12px;\n"
"}")
        self.widget_calendar_2.setObjectName("widget_calendar_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_calendar_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_calendar_2 = QtWidgets.QTableWidget(parent=self.widget_calendar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_calendar_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_calendar_2.setSizePolicy(sizePolicy)
        self.tableWidget_calendar_2.setObjectName("tableWidget_calendar_2")
        self.tableWidget_calendar_2.setColumnCount(0)
        self.tableWidget_calendar_2.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget_calendar_2)
        self.horizontalLayout_2.addWidget(self.widget_calendar_2)
        self.widget_calendar_3 = QtWidgets.QWidget(parent=self.widget_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_calendar_3.sizePolicy().hasHeightForWidth())
        self.widget_calendar_3.setSizePolicy(sizePolicy)
        self.widget_calendar_3.setStyleSheet("QWidget {\n"
"    background: #FFFFFF;\n"
"\n"
"    color: #1C1C1E;\n"
"\n"
"    font-family: \"SF Pro Text\", \"Helvetica Neue\", \"Helvetica\", \"Arial\";\n"
"    font-size: 13px;\n"
"\n"
"    border: 1px solid #D8D8DB;\n"
"    border-radius: 12px;\n"
"}")
        self.widget_calendar_3.setObjectName("widget_calendar_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_calendar_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget_calendar_4 = QtWidgets.QTableWidget(parent=self.widget_calendar_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_calendar_4.sizePolicy().hasHeightForWidth())
        self.tableWidget_calendar_4.setSizePolicy(sizePolicy)
        self.tableWidget_calendar_4.setObjectName("tableWidget_calendar_4")
        self.tableWidget_calendar_4.setColumnCount(0)
        self.tableWidget_calendar_4.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget_calendar_4)
        self.horizontalLayout_2.addWidget(self.widget_calendar_3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.widget_info, 0, 0, 1, 1)
        self.widget_calculations = QtWidgets.QWidget(parent=CASH)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_calculations.sizePolicy().hasHeightForWidth())
        self.widget_calculations.setSizePolicy(sizePolicy)
        self.widget_calculations.setStyleSheet("QWidget {\n"
"    background: #F1F2F3;\n"
"\n"
"    color: #1C1C1E;\n"
"\n"
"    font-family: \"SF Pro Text\", \"Helvetica Neue\", \"Helvetica\", \"Arial\";\n"
"    font-size: 13px;\n"
"\n"
"    border: 1px solid #D8D8DB;\n"
"    border-radius: 12px;\n"
"}")
        self.widget_calculations.setObjectName("widget_calculations")
        self.gridLayout_7.addWidget(self.widget_calculations, 2, 0, 1, 1)

        self.retranslateUi(CASH)
        QtCore.QMetaObject.connectSlotsByName(CASH)

    def retranslateUi(self, CASH):
        _translate = QtCore.QCoreApplication.translate
        CASH.setWindowTitle(_translate("CASH", "CASH"))
        self.label_title.setText(_translate("CASH", "Кол-во дней"))
        self.label_calendar.setText(_translate("CASH", "календарных"))
        self.label_weekend.setText(_translate("CASH", "вых./праздн."))
        self.label_work.setText(_translate("CASH", "рабочих"))
        self.label_day_zp.setText(_translate("CASH", "день ЗП:"))
        self.label_day_avans.setText(_translate("CASH", "день аванса:"))
