# Form implementation generated from reading ui file 'ui/cash.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CASH(object):
    def setupUi(self, CASH):
        CASH.setObjectName("CASH")
        CASH.resize(1217, 876)
        CASH.setStyleSheet("QWidget {\n"
"    background-color: white;\n"
"}")
        self.gridLayout_7 = QtWidgets.QGridLayout(CASH)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_3 = QtWidgets.QWidget(parent=CASH)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setStyleSheet("QWidget {\n"
"    background: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #F6F7F8,\n"
"        stop: 1 #ECEDEF\n"
"    );\n"
"\n"
"    color: #1C1C1E;\n"
"\n"
"    font-family: \"SF Pro Text\", \"Helvetica Neue\", \"Helvetica\", \"Arial\";\n"
"    font-size: 13px;\n"
"\n"
"    border: 1px solid #D8D8DB;\n"
"    border-radius: 12px;\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_7.addWidget(self.widget_3, 2, 0, 1, 1)
        self.widget_1 = QtWidgets.QWidget(parent=CASH)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_1.sizePolicy().hasHeightForWidth())
        self.widget_1.setSizePolicy(sizePolicy)
        self.widget_1.setStyleSheet("")
        self.widget_1.setObjectName("widget_1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_1)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.widget_2)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)
        spacerItem = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_day_zp = QtWidgets.QLabel(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_day_zp.sizePolicy().hasHeightForWidth())
        self.label_day_zp.setSizePolicy(sizePolicy)
        self.label_day_zp.setObjectName("label_day_zp")
        self.horizontalLayout.addWidget(self.label_day_zp)
        self.spinBox_zp = QtWidgets.QSpinBox(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_zp.sizePolicy().hasHeightForWidth())
        self.spinBox_zp.setSizePolicy(sizePolicy)
        self.spinBox_zp.setObjectName("spinBox_zp")
        self.horizontalLayout.addWidget(self.spinBox_zp)
        self.label_day_avans = QtWidgets.QLabel(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_day_avans.sizePolicy().hasHeightForWidth())
        self.label_day_avans.setSizePolicy(sizePolicy)
        self.label_day_avans.setObjectName("label_day_avans")
        self.horizontalLayout.addWidget(self.label_day_avans)
        self.spinBox_avans = QtWidgets.QSpinBox(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_avans.sizePolicy().hasHeightForWidth())
        self.spinBox_avans.setSizePolicy(sizePolicy)
        self.spinBox_avans.setObjectName("spinBox_avans")
        self.horizontalLayout.addWidget(self.spinBox_avans)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addWidget(self.widget_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.widget_1, 0, 0, 1, 1)

        self.retranslateUi(CASH)
        QtCore.QMetaObject.connectSlotsByName(CASH)

    def retranslateUi(self, CASH):
        _translate = QtCore.QCoreApplication.translate
        CASH.setWindowTitle(_translate("CASH", "CASH"))
        self.label_day_zp.setText(_translate("CASH", "день ЗП:"))
        self.label_day_avans.setText(_translate("CASH", "день аванса:"))
